$:
  vscode:
    - docker:
        image: cnbcool/default-dev-env:latest
      services:
        - vscode
        - docker
      stages:
        - name: install edgeone
          script: npm install edgeone -g

  push:
    - imports: https://cnb.cool/magiccode1412/secret/-/blob/main/env.yml
      stages:
        - name: sync_to_github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/${GITHUB_USERNAME}/${CNB_REPO_NAME_LOWERCASE}.git
            auth_type: https
            username: "${GITHUB_USERNAME}"
            password: "${GITHUB_ACCESS_TOKEN}"
            force: true

main:
  push:
  - stages:
    - name: notify
      image: cnbcool/webhook
      settings:
        urls:
          - https://api.edgeone.ai/eo/pages/hook/cnb
        method: POST
        content_type: application/json
        template: |
          {
            "repoName": "{{ CNB_REPO_NAME }}",
            "repoUrl": "{{ CNB_REPO_URL_HTTPS }}",
            "branch": "{{ CNB_BRANCH }}",
            "commit": "{{ CNB_COMMIT_SHORT }}",
            "commitMessage": "{{ CNB_COMMIT_MESSAGE }}",
            "committer": "{{ CNB_COMMITTER }}",
            "event": "{{ CNB_EVENT }}",
            "buildId": "{{ CNB_BUILD_ID }}",
            "buildWebUrl": "{{ CNB_BUILD_WEB_URL }}",
            "buildUser": "{{ CNB_BUILD_USER }}",
            "pipelineName": "{{ CNB_PIPELINE_NAME }}"
          }