name = "repo-watcher"
main = "src/index.js"
compatibility_date = "2026-03-01"
keep_vars = true

[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.svg"]
fallthrough = true

[[kv_namespaces]]
binding = "KV_DEFAULT"